/*
 * generated by Xtext 2.25.0
 */
package su.nsk.iae.edtl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EdtlRuntimeModule extends AbstractEdtlRuntimeModule {
}
